import { sql } from "drizzle-orm";
import { index, integer, primaryKey, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

// Better Auth tables (admin login), generated by `@better-auth/cli generate`.
export * from "./auth-schema";

const createdAt = () =>
  integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .default(sql`(unixepoch('subsec') * 1000)`);

export const devices = sqliteTable("devices", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  status: text("status", { enum: ["enabled", "disabled"] }).notNull().default("enabled"),
  notes: text("notes"),
  createdAt: createdAt(),
  deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),
  lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }),
  lastIp: text("last_ip"),
});

export const deviceTokens = sqliteTable(
  "device_tokens",
  {
    id: text("id").primaryKey(),
    deviceId: text("device_id").notNull().references(() => devices.id),
    tokenHash: text("token_hash").notNull(),
    // First chars of the raw token, for identifying it in the UI without revealing it.
    tokenPrefix: text("token_prefix").notNull(),
    createdAt: createdAt(),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
    revokedAt: integer("revoked_at", { mode: "timestamp_ms" }),
  },
  (t) => [uniqueIndex("device_tokens_hash_idx").on(t.tokenHash), index("device_tokens_device_idx").on(t.deviceId)],
);

export const enrollmentCodes = sqliteTable("enrollment_codes", {
  id: text("id").primaryKey(),
  deviceId: text("device_id").notNull().references(() => devices.id),
  codeHash: text("code_hash").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  usedAt: integer("used_at", { mode: "timestamp_ms" }),
  attempts: integer("attempts").notNull().default(0),
  createdAt: createdAt(),
});

export const models = sqliteTable("models", {
  id: text("id").primaryKey(), // 'opus' | 'sonnet' | 'haiku' | ...
  displayName: text("display_name").notNull(),
  // Provider model ids starting with this prefix resolve to this model.
  matchPrefix: text("match_prefix").notNull().unique(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
});

export const deviceModels = sqliteTable(
  "device_models",
  {
    deviceId: text("device_id").notNull().references(() => devices.id),
    modelId: text("model_id").notNull().references(() => models.id),
  },
  (t) => [primaryKey({ columns: [t.deviceId, t.modelId] })],
);

// NULL limit = unlimited.
export const devicePolicies = sqliteTable("device_policies", {
  deviceId: text("device_id").primaryKey().references(() => devices.id),
  defaultModelId: text("default_model_id").references(() => models.id),
  dailyRequests: integer("daily_requests"),
  weeklyRequests: integer("weekly_requests"),
  dailyTokens: integer("daily_tokens"),
  weeklyTokens: integer("weekly_tokens"),
  requestsPerMinute: integer("requests_per_minute"),
  maxConcurrent: integer("max_concurrent"),
});

// Append-only; doubles as the request log. Never stores prompt/response bodies.
export const usageEvents = sqliteTable(
  "usage_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    requestId: text("request_id").notNull(),
    deviceId: text("device_id").notNull().references(() => devices.id),
    ts: integer("ts", { mode: "timestamp_ms" }).notNull(),
    endpoint: text("endpoint").notNull(),
    model: text("model"),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    cacheCreationTokens: integer("cache_creation_tokens").notNull().default(0),
    // Subset of cacheCreationTokens written with a 1-hour TTL, which costs 2x input instead of 1.25x.
    cacheCreation1hTokens: integer("cache_creation_1h_tokens").notNull().default(0),
    cacheReadTokens: integer("cache_read_tokens").notNull().default(0),
    // What this request would have cost at Anthropic's public API rates; NULL when the model has
    // no published price. See lib/pricing.ts.
    costUsd: real("cost_usd"),
    statusCode: integer("status_code").notNull(),
    // Gateway-side outcome when the request never reached upstream, e.g. MODEL_NOT_ALLOWED.
    errorType: text("error_type"),
    aborted: integer("aborted", { mode: "boolean" }).notNull().default(false),
    latencyMs: integer("latency_ms").notNull(),
    clientIp: text("client_ip"),
  },
  // Device and model indexes serve the scoped views; the bare ts index serves fleet-wide
  // time-range scans, which are the usage explorer's default.
  (t) => [
    index("usage_events_device_ts_idx").on(t.deviceId, t.ts),
    index("usage_events_model_ts_idx").on(t.model, t.ts),
    index("usage_events_ts_idx").on(t.ts),
  ],
);

// Singleton row (id = 1), refreshed from anthropic-ratelimit-unified-* response headers.
export const upstreamQuota = sqliteTable("upstream_quota", {
  id: integer("id").primaryKey(),
  fiveHourUtil: real("five_hour_util"),
  fiveHourReset: integer("five_hour_reset", { mode: "timestamp_ms" }),
  weeklyUtil: real("weekly_util"),
  weeklyReset: integer("weekly_reset", { mode: "timestamp_ms" }),
  status: text("status"),
  // Every unified-* header as received, including model-specific buckets.
  raw: text("raw", { mode: "json" }).$type<Record<string, string>>().notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const auditEvents = sqliteTable(
  "audit_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    createdAt: createdAt(),
    adminUserId: text("admin_user_id"),
    action: text("action").notNull(),
    targetType: text("target_type").notNull(),
    targetId: text("target_id"),
    before: text("before", { mode: "json" }),
    after: text("after", { mode: "json" }),
    ip: text("ip"),
    userAgent: text("user_agent"),
  },
  (t) => [index("audit_events_created_idx").on(t.createdAt), index("audit_events_target_idx").on(t.targetType, t.targetId)],
);
